### ISSUE TITLE
UI integration

### ISSUE THREAD

**Issue by erikrakuscek** [luxdefi/ui#8]
High priority (main components needed for chatbot)

- [x] textarea - https://ui.lux.finance/docs/components/textarea
- [x] select - https://ui.lux.finance/docs/components/select
- [x] switch - https://ui.lux.finance/docs/components/switch
- [ ] date picker - https://ui.lux.finance/docs/components/date-picker
- [ ] combobox - https://ui.lux.finance/docs/components/combobox
- [ ] data table - https://ui.lux.finance/docs/components/data-table
- [x] checkbox - https://ui.lux.finance/docs/components/checkbox
- [x] tabs - https://ui.lux.finance/docs/components/tabs
- [x] popover - https://ui.lux.finance/docs/components/popover

Medium priority

- [x] avatar - https://ui.lux.finance/docs/components/avatar
- [x] progress - https://ui.lux.finance/docs/components/progress
- [x] separator - https://ui.lux.finance/docs/components/separator
- [ ] label - https://ui.lux.finance/docs/components/label

Low priority

- [x] skeleton - https://ui.lux.finance/docs/components/skeleton
- [x] scroll area - https://ui.lux.finance/docs/components/scroll-area

**Comment by artemis-prime** [comment]
date picker, combobox, data table are all not components but like recipes for using other components.  I'll level that as an exercise for the reader ;)

label was already there.
